### ISSUE TITLE
Fabric not compiling with github.com/prometheus/client_golang v1.14.0.

### ISSUE THREAD

**Issue by denyeart** [hyperledger/fabric#4052]
Attempted to bump github.com/prometheus/client_golang to v1.14.0.

It compiles on mac and alpine, but in our ubuntu docker image target "make docker-clean docker" it fails with:
`vendor/github.com/prometheus/client_golang/prometheus/registry.go:63:15: undefined: NewGoCollector`

It has something to do with the build tag where NewGoCollector is defined at:
https://github.com/prometheus/client_golang/blob/v1.14.0/prometheus/go_collector_latest.go#L14-L15

With that build tag it should work on Go 1.17 and above, while we're currently at go 1.18.10.

**Comment by davidkel** [comment]
It appears that any file of the form *latest.go just doesnt get added to the container, no idea why. Tried COPY but it exhibited the same issue. No `.dockerignore` file in the code tree specifies excluding this pattern that I could find. Tried tar'ing up the source tree and using ADD to copy and expand the source tree works and the file was present in the docker build container layer.

**Comment by pfi79** [comment]
@denyeart maybe we should close it down.

**Comment by denyeart** [comment]
@davidkel 

You were on the right track last year... the dockerignore was to blame - `**/*test.go` entry matched to `latest.go`!

Thanks to @pfi79 for tracking it down.
